
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRitTaTY0VmMyUE13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBME1Ea3dPVEV3TUROYUZ3MHpOakEwTURZd09URTFNRE5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURKb0RPbVRsMWFKdUFVNG5UV1VWeUhNUnd4Vkc2RkMxbXAwN0EwWFpjeVBLKytLR0QwVXJJaGh4Vi8KZmRwVGIzZnBVZ1Vhc1FRTlAxSHlBOUpwSDlLUWxVVmROU2xnaTd5aEszRDBDYkFXaENOM3FYRE9kWjZEZElrZAptc2hwMGEvK2JYRHBFeVJxaW9rOTUyb3lQL2Y3ZGE0NWY5TGpEb0tmVWFhOWVOWlJKRkhkbStROUg0M2V2Z081ClB1ZExFUkZ2bDRST3AzelQ2SXd6dXVwdFlOU2RjWXI0NzV3YXkxdE5CTzNZYVIySlkySGNwZm1OMmhnZSt4Qm8KenlHSXR1TFFzMVlFNWVlNDZWZExrNFM5Mi8vNWVWNmw3RjJubWVmZWc5K2dhNGw1eVZnNVpmTHFiUittcm9VSgpIWFp4VG5DS3hoRXVMUEZVSUxaeGUzZEhsYVJsQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRUmxHQ1BsWWI4Rmd1NEFMelVPN1lja3gyU2Z6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0d0eFJkV2lvTgpGSWVsajBCdWhNdk0yNWt5YkJjQjljSkVLYkpWWHhJOTFjcnpodWNBMzZrQ25lUzEzMjA3YWZhUkliZ2xHeUNmCi9rZklueWxESVlhT0ZZc0FXY2NZd2x1eHgvYmR6elYyeFRZdmNCUDFBOGpJYkpuenhsczU2Wmg3L0ZCK0dHU2IKMkFoM1ozM0dQZU1KcUFNenlRNXBVdnNLVVI1UUV6dEIrYytKcFpNNmx3MFd5NUlTOU1jRVBWZ2lJTnQ4dVRLZApxQUEvTGpNV3Bwam53US9XQit0WmZ0S0tES1VZcTVvd2dNTUNOMmNYTDlDdVJoQmh4TnVWS1FETmNJZytoaEtRCmRJVVc1cXZRbkFDaU5WMmwxMU5UYXhEMmpMVlJ0YmRYSzdwR2VwdUJKZkZTYUtKM1k5YmxnUUdNNW1mMnVnTDIKcWpBYUNJYzl1VmpMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://d46cb067-0c5b-451a-addf-e6276d6dbd70.uk-lon-1-gw.linodelke.net:443
  name: lke590012

users:
- name: lke590012-admin
  user:
    as-user-extra: {}
    token: xxxx

contexts:
- context:
    cluster: lke590012
    namespace: default
    user: lke590012-admin
  name: lke590012-ctx

current-context: lke590012-ctx
